using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TTBattleSim.Entities
{
	public class CogTaunts
	{
		public string[] taunts = { 
			"I'm gonna tell the boss about you!",
			"I may just be a flunky - but I'm real spunky.",	
			"I'm going to use you to step up the corporate ladder.",
			"You're not going to like the way I work.",
			"I'm going to rub you out!",
			"Hey, you can't push me around.",
			"I'm No. 2!",
			"I'm going to scratch you out.",
			"You need some positive enforcement.",
			"I haven't been wrong yet.",
			"Want to meet? I say yes, anytime.",
			"I won't take no for an answer.",
			"We're going to do this my way.",
			"Well, you've managed to find me.",
			"I can be very intimidating.",
			"I'll take care of you in no time.",
			"Why do you look so down?",
			"You've just become expendable.",
			"You're going down!",
			"Expect diminishing returns.",
			"You are going to have such a headache.",
			"Heads up!",
			"I'll have your head for this.",
			"You'll wish this was all in your head.",
			"RAID!",
			"You don't fit in my corporation.",
			"Prepare to be raided!",
			"Looks like you're primed for a take-over.",
			"I'm going to make mozzarella outta ya.",
			"I've been told I'm very strong.",
			"You can call me Jack.",
			"I'm going to cream you!",
			"Oh goody, lunch time.",
			"I'm ready to feast!",
			"I'm a sucker for Toons.",
			"Let's talk about the bottom line.",
			"I'm going to make you dizzy.",
			"I'm going to leave you high and dry.",
			"You're soon going to need a cookie and some juice.",
			"I'm going to need to do a quick count on you.",
			"You're not going to like my double play.",
			"I'm going to give you double the trouble.",
			"You may want to double up against me.",
			"You may want to double-think this.",
			"I'm going to chase you out of town!",
			"This is no laughing matter.",
			"It's all uphill from here.",
			"I'm going to enjoy this.",
			"You won't be coming back.",
			"Take that back or else!",
			"I'm good at cutting costs.",
			"You're going to have a stabbing headache soon.",
			"You'll never know when I'll stop.",
			"Care to take a few turns with me?",
			"The doctor is in, the Toon is out.",
			"I have my own special spin on the subject.",
			"This is so much fun it should be illegal.",	
			"I soar, then I score.",
			"You should know, I have some killer instincts.",
			"There is no limit to my talons.",
			"You're in big trouble!",
			"I'm going to wig out on you.",
			"I'm a big deal, little Toon.",
			"Court is in session.",
			"I will make short work of you.",
			"You're about to have money trouble.",
			"You're about to be overcharged.",
			"This will be a short-term assignment.",
			"Heads, I win, tails, you lose.",
			"I'm going to give you a pinch for luck.",
			"A Penny for your Gags.",
			"I'm going to put a crimp in your smile.",
			"That's Mr. Tightwad to you.",
			"I'm going to make a big dent in your budget.",
			"You'll find I'm very tightfisted.",
			"I'm going to cut off your funding.",
			"I can hurt you where it counts.",
			"I've bean waiting for you.",
			"I enjoy subtracting Toons.",
			"I make every bean count.",
			"Is it time for crunch already?",
			"Where would you like to have your crunch today?",
			"Now you're really in a crunch.",
			"This will not be smooth.",
			"You're about to have money trouble.",
			"You can never have too much money!",
			"I can bag this.",
			"Money will make your world go around.",
			"It's time to collect on your loan.",
			"Your loan is now due.",
			"Time to pay up.",
			"Well, you asked for an advance and you've got it.",
			"Stick 'em up.",
			"You've been robbed.",
			"I'll rob you of this victory.",
			"You could call this neighborhood robbery.",
			"Boy, did you get your wires crossed.",
			"I was hoping you'd answer my call.",
			"You rang?",
			"I'm going to cause a ringing sensation.",
			"I plan on making this inconvenient for you.",
			"I'm prepared to close this deal quickly.",
			"This a bad time? Good.",
			"You should have missed my call.",
			"You name it, I've dropped it.",
			"In my opinion, your name is mud.",
			"Let's hurry, I'm having lunch with 'Mr. Hollywood'.",
			"Have I mentioned I know 'The Mingler'?",
			"Let me show you some of my handiwork.",
			"Let's seal the deal.",
			"Let's shake on it.",
			"Put it there, Toon.",
			"I feel moved to defeat you.",
			"Are you shaking yet?",
			"I'm ready to make my move.",
			"This should be a moving moment.",
			"You don't know who you're facing.",
			"It's time to face-off!",
			"You're in for two times the trouble.",
			"You better face up to defeat.",
			"Are you sure you're ready to mingle?",
			"You don't know who you're mingling with.",
			"I'm going to mingle in your business.",
			"Ever mingle with the likes of me?",
			"I'm ready to rock and roll your end credits.",
			"Today the role of defeated Toon will be played by - YOU!",
			"I hope you don't forget your lines.",
			"This scene will go on the cutting room floor."
		};
	}
}
